### ISSUE TITLE
[Sidesøk] - Oppslag på KNR/BNR/GNR

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/forvaltningsportal#1]
Edit 2: satte opp #182 for forbedring av resultat i søk, så denne kan ferdigstilles og testes for funksjon.

Edit 1:
- knr + bnr + gnr er SAMMEN unike
- knr er diffust, søke på kommunenr/kommunenavn
- kan i klikkikart få opp knr/bnr/gnr?
--------

- knr=x,gnr=y,bnr=z (ett direkte oppslag)
- rene tall (gir tre søk, ett i knr, ett i gnr og ett i bnr)
- x-y-z eller x-y- eller x-y eller x-
- x y z eller x y  (og varianter med mellomrom hvorsomhelst)
- x/y/z eller x/y/ eller x/y eller x/
- x;y;z eller x;y; eller x;y eller x;
- x,y,z eller x,y, eller x,y eller x,
- andre komboer av de ovenfor som f.eks x-y/z som vi vet de liker å bruke
- og alle kombinasjoner av de ovenfor (mellomrom, bindestrek, komma, semikolon og slash), i inntil tre nummer. Her gjør den ett oppslag med variablene i antatt riktig rekkefølge.
- om de har to bindestreker og to slasher har de feilet. om de starter med bindestrek blir det og feil. får være grenser for hva man tar høyde for.

**Comment by bjornreppen** [comment]
Etterhvert kunne problemet forenkles til å fra klienten kalle på
https://ws.geonorge.no/adresser/v1/sok?kommunenummer=5001&gardsnummer=439&bruksnummer=171&treffPerSide=20&side=0
