### ISSUE TITLE
Søk: Hjelpetekst

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/forvaltningsportal#100]
Edit 02.06.2020:
- eksempel nedenfor vil ikke fungere. 
- Trenger vi hjelpetekst?
- Isåfall, @runningbones, hva skal den være?

----

Kan legge inn hjelp/beskrivelse i popup på søk når bruker har cursor i søkefelt, ala www.norgeskart.no.

"Du kan søke på adresse, stedsnavn eller koordinater.
For eksempel:
Wergelandsveien1, Oslo
0301-209/416
Slottsparken
6649900,261205
For flere søkevarianter, se under tips og triks i menyen."

**Comment by bjornreppen** [comment]
![image](https://user-images.githubusercontent.com/281359/88983042-1bcf0400-d2ca-11ea-8d66-bab9a9baecb4.png)
