### ISSUE TITLE
[Bakgrunnskart] Fjerne dem fra kartlag, dytte leverandør osv nederst.

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/forvaltningsportal#102]
- [x] Fjerne fra kartlag @bjornreppen
- [x] Hente kildenavn og url @runningbones
- [x] Presentere det i kartløsningen @helemork

**Comment by runningbones** [comment]
Spørsmål om struktur på kildenavn og URL:

1. Kildenavn: Title fra xml?
2. URL: Get Capabilites Url?
3. Skal vi ta med kilde/dataeier?

**Comment by runningbones** [comment]
Bakgrunnkart navn | Bakgrunnkart navn - alternativ | Dataeier | Logo
-- | -- | -- | --
GEBCO | GEBCO | GEBCO/Kartverket | https://www.gebco.net/images/gebco-logo.png
Topografisk   norgeskart 4 | TOPO4 | Kartverket | https://www.kartverket.no/globalassets/logoer/kartverket_staende_web.png
Topografisk norgeskart 4 Gråtone | TOPO4 Gråtone | Kartverket | https://www.kartverket.no/globalassets/logoer/kartverket_staende_web.png
