### ISSUE TITLE
Faktaark naturtyper mdir

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/forvaltningsportal#104]
Faktaark for naturtyper fra mdir må inneholde en id fra det enkelte objekt for å få url til riktig faktaark

**Comment by helemork** [comment]
- legg til faktaark-url type generisk til hovedkartlagmeny
- fiks id osv til klikk-i-kart

**Comment by bjornreppen** [comment]
Dette er på plass.  Faktaark-urlen kan nå settes opp til å bruke urlen som finnes i GetFeatureInfo-responsen.
