### ISSUE TITLE
Etablere automatisert nedlasting av data fra geonorge

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/forvaltningsportal#11]
Etablere automatisert nedlasting av data fra geonorge i egen db for bruk i klient. 

https://nedlasting.geonorge.no/Help

**Comment by runningbones** [comment]
#49

**Comment by bjornreppen** [comment]
https://github.com/kartverket/Geonorge.NedlastingKlient/issues/3

**Comment by helemork** [comment]
- magler rute for config fil
- server -> arb.stasjon
- løser kun at vi ikke har gamle versjoner
- må likevel skreddersy litt
