### ISSUE TITLE
Kartlag underlagsvarianter - databasemodeller og implementering 

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/forvaltningsportal#137]
- [x] mulighet til å legge til sub-lag for et lag, f.eks dekningskart 
- [x] alle sublag påtvinges å ha et hovedlag
- [x] alle sublag kan opprettes fra kartlag 
- [x] sublag benytter hovedlagets wmsurl, og har kun iboende wmslayer
- [ ] felt for prioritering/default. 
- [ ] datamigrering som får alle eksisterende wmslayers til å opprettes som egne underlag i tilhørende riktig modell med de rette attributtene, dytt ned samme tittel, legendeurl, dytt ned at alle er på initielt ++
- [ ] her må noen manuelt få kose seg med navneendringer i ettertid vil jeg tro

**Comment by runningbones** [comment]
1.  Arter av nasjonal forvaltningsinteresse: https://kart.miljodirektoratet.no/arcgis/services/artnasjonal/MapServer/WmsServer?
2. Artskart wms: http://kart.artsdatabanken.no/WMS/artskart.aspx?version=1.3.0
3. KLG-kart fra ADB

**Comment by helemork** [comment]
Kan du spesifisere litt mer:
- Hva vil du ha som overkart
- Hva vil du ha som underkart
- Hvor mange typer underkart
- Hva mer trenger de enn wms-lag? tittel? om de er av/på per default?

**Comment by runningbones** [comment]
Trenger nye felt i django for wms_layer og wms_layer_name. Trenger i tillegg toggle/checkbox for av/på. Antall "underkart/wmslayers" er potenisielt høyt. Er det mulig å få til "add new wms_layer" med en maks antall på f.eks. 15 per "kartlag"

**Comment by helemork** [comment]
Det jeg tenker er at vi lager en ny modell kalt underlag eller noe slikt som du kobler opp på ete eksisterende lag, på samme måte som når du la til tags og sånn. Mine tanker om denne modellen er at den inneholder følgende:

* navn på lag
* wms_layer (url'en)
* wms_layer_name (er dette samme som navn på lag, eller noe dere bruker for å hente ut en attr?)
* av/på

Laget kobles så i en en-til-en relasjon med et "vanlig" lag, som alltid vil være defaulten. 
Det vil si at det dyttes inn som en underkategori av dette laget, sånn som når du legger til hvem som er dataeier. Da får du muligheten til å opprette nye lag innefra selve laget sånn som man kan lage nye tags og nye dataeiere fra inne i et kartlag. Men den vil kun kunne knyttes til ett lag.

Høres det bra ut?

**Comment by runningbones** [comment]
Høres bra ut. Tror også feltet "Legendeurl:" bør kobles til det enkete "underlag" (alt. navn kan være "sub_layer"

**Comment by helemork** [comment]
Den er grei. Da endrer jeg denne issuen til oppsett, og setter den over på meg i min next up :)
