### ISSUE TITLE
Spøkelser

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/forvaltningsportal#140]
- Ø tar opp dette med dataleverandør

**Comment by runningbones** [comment]
Problemet forsvinner om vi benytter riktig API (ikke nin_innsyn/nin_flat_struktur, men https://kart.miljodirektoratet.no/arcgis/rest/services/naturtyper_nin/MapServer)

**Comment by helemork** [comment]
@bjornreppen fix?
