### ISSUE TITLE
Penere fremstilling av kartlaglisten

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/forvaltningsportal#161]
- [x] Stor klikkflate på mobilelement, mer kompakt ellers
- [x] Underlag bør fremstilles mer kompakt og som ordentlige elementer
- [x] Dytt ut lag alfabetisk om ikke annen visning er valgt
- [x] Mobil-tweaks
- [x] Infobox og Søk i alle-kartlag-boks -> sistnevnte bør dekke hele, ikke deler og heller dytte samme info på nytt.
- [x] Ekspander og gå til nettsideknapp står for tett og ser ikke ut som knapp. løsning?

**Comment by helemork** [comment]
hvor kompakte er ønskelig? 
- husk man skal ha plass til å trykke på dem med en finger også, så det kan ikke bli for trangt. 
- er det andre relaterte tweaks på lista vi bør ta samtidig? så langt har fokuset på mobil vært minimalt, bare å få det til å fungere uten å være spesielt gjennomtenkt/funksjonelt.

**Comment by bjornreppen** [comment]
Store hvis man er på en enhet hvor man bruker finger (mobil/pad) ... små hvis man bruker pc/mus?

Fjerne zoom-knapper, søkefelt og kartlagliste på mobil (helt til man har trykket på en knapp som åpner dem)?

**Comment by helemork** [comment]
Fikser de mest kritiske tingene på hvor stor plass ting tar og setter opp en PR på det, og så tenker jeg vi venter med mer beautification til vi har tenkt på hvordan det skal være. :)

**Comment by runningbones** [comment]
Tillegg etter møtet 08.06.2020:
- [ ] Behold søk i skjermen når man skjuler kartlagslista

**Comment by runningbones** [comment]
Sortering av liste (alfabetins/tema/dataeier vs filtrering (emneknagg): Egne knapp for de to funksjonene. Forlsag:
https://materialdesignicons.com/icon/sort-variant 
https://materialdesignicons.com/icon/filter
