### ISSUE TITLE
GetFeatureInfo - autogenerering fra felter i admin

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/forvaltningsportal#169]
Undersøk mulighet for å autogenerere GetFeatureInfo-url (klikkURL). 

Inspirasjon: https://astuntechnology.github.io/osgis-ol3-leaflet/leaflet/05-WMS-INFO.html

Layers ligger jo alt inne i kartlag  (Wmslayer), og mye bør kunne settes default (eks .espg, latlng/bbox/info_format+++) 

Om dette fungererer bør det som er manuelt å "velge" rett attributt for "kikktekst" og evt. faktaark

**Comment by runningbones** [comment]
Eks. på en som faktisk fungerer: https://wms.nibio.no/cgi-bin/skogbruksplan?version=1.1.0&srs=EPSG:4326&feature_count=1&info_format=application/vnd.ogc.gml&layers=Livsmiljoer&query_layers=Livsmiljoer&x=128&y=128&height=255&width=255&request=GetFeatureInfo&service=WMS&bbox={bbox}

**Comment by helemork** [comment]
Er ikke dette egentlig en kopi av #165 ?

**Comment by runningbones** [comment]
Ikke duplikat av #165 , men svært relatert. Tror begge i stor grad løses av #190
