### ISSUE TITLE
Brukertest - direktoratsgruppe

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/forvaltningsportal#185]
De første ukene av juni vil direktoratsgruppa bli bedt om å gi tilbakemelding på https://forvaltningsportal.test.artsdatabanken.no/

Tror vi lager et tilpasset webskjema hvor vi spesifikt ber om tilbakemeldinger på konkret punkter. Dette webskjemaet kan vi kanskje lenke til fra https://forvaltningsportal.test.artsdatabanken.no/. 

Tror vi primært skal be om tilbakemelding på to hovedtema: data og funksjonalitet.
 - DATA:
1. For dataeiere:  Er de innmeldte datasettene tilgjengelig i riktig variant? Skal andre underlag inn/evt. byttes ut med noen av de som allerede er der? Er taggingen av datasettene riktig 
2. Klikk i kart: Gir klikk i kart treff på fornuftige felter i dataeiers attributtabell? Hvor bør vi justere?
3. Er det brukt fornuftige tagger? hvilke mangler? hvilke bør endres/fjernes?

- Funksjonalitet:

1. Slå av/på kartlag: 
2. Finne tegnforklaring
3. Finn metadata (geonorge/produktark+++)
4. identidfisere objekter i kartet
5. Finne fram til et kjent sted ved hjelp av søkefeltet
6. Finne data fra kartlag osm ikke er aktive vha klikk i kart - skru på det aktuelle kartlaget
7. Sortere lista over kartlag etter tema, dataeier. 
8. Filtrere kartlagsliste etter tagg

Åpne kommentarfelt for annen tilbakemelding og ønsker

Forslår at vi legger inn ikke obligatoriske felter for navn/etat/epost i skjemaet for mulighet til dialog dersom uklarhet.

**Comment by helemork** [comment]
Høres bra ut, men da har vi kort tid på å få ferdig hvordan søk osv fungerer. Foreslår isåfall økt prioritet på det.

**Comment by runningbones** [comment]
https://forms.gle/YRQxYUCirjFH7Rwe6
