### ISSUE TITLE
4. [Datasett] - Markering av tema | Felt for tema [13]

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/forvaltningsportal#19]

**Comment by helemork** [comment]
@bjornreppen og @runningbones 

- I kartlag jsonen har vi allerede tema som en struktur, nøstet som dict under språk. Tenker vi kan la den stå som den er.
- Det kan se ut som om noen lag ikke har tema, de kan vi jo dytte sammen i visning sin temaløse.
- Om man skal ha andre tags en tema, er det liten vits for meg å bruke tid på å "finne opp" noen før vi har konkrete eksempler på hva de skal være. Med andre ord,
- denne issuen er blokkert av diskusjon med gruppen.
- Å lage uthenting basert på en liste med tags er en annen issue, #16, tenker jeg bruker dummy data på den der.

**Comment by runningbones** [comment]
Prematurt forslag:

  | Landskap | Arter | Naturtyper | Miljøvariabler og økologiske grunnlagsdata | Dataeier (hver eier egen tag?) | Administrative kartlag | DOK-data | Modellerte data | Feltkartlagte data
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
NiN Landskap | x |   |   |   | x |   | x | x |  
Mdir Naturtyper NiN |   |   | x |   | x |   | x |   | x
Naturvernområder |   |   |   |   | x | x | x |   |  
Fylker/Kommuner |   |   |   |   | x | x |   |   |  
Kalkinnhold |   |   |   | x | x |   |   |   | x
NIBIO Livsmiljø |   |   | x |   | x |   |   |   | x
NIBIO arealressurs |   |   | x |   | x |   | x |   | x

**Comment by helemork** [comment]
Da starter jeg med denne listen, og så tar vi det derfra.

**Comment by helemork** [comment]
Lagt til: sortering på tema og dataeier
Usikker på hvordan vi vil ha denne:

jeg tenkte 

- tema: en på hver, sånn at overskriften gir sorteringsgrunnlag?
- tags: alle kan ha flere, typ de i lista ovenfor. brukes for sortering og filtrering?

men nå har f.eks en av dem tema: skog 
er litt forvirra på god løsning
