### ISSUE TITLE
KNR/GBR/BNR i klikk-i-kart

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/forvaltningsportal#191]
Ønsker at kommunenummer/gårdsnummer/bruksnummer blir synlig ved klikk i kart: 
![image](https://user-images.githubusercontent.com/31729342/83510551-77009800-a4cd-11ea-8f62-eb2d011e3b1d.png)

**Comment by runningbones** [comment]
Kan legges inn som en streng mellom fylke og lat/lng

**Comment by runningbones** [comment]
Bør vurdere å sette max zoomnivå for treff: https://wiki.openstreetmap.org/wiki/Zoom_levels (samme for adresse): Forslag: adresse, gnr/bnr++ gir trekk i "klikkikart" ved zoomlevel 15
