### ISSUE TITLE
Django - endringer av felt

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/forvaltningsportal#192]
#165 #190 #169 

Klikkurl: Felt og feltnavn i Django beholdes. Forskjellen er arbeidsflyt i hvordan finne riktig url (skalk nå hentes manuelt fra mapadmin (TM) fra @bjornreppen)
LegendeURL: Kan autogenereres/finnes ved å kombinere wmslayer og data fra XML-respons fra WMSurl i mapadmin(TM) fra @bjornreppen , men ikke veldig viktig. Blir uansett mye crtl c, ctrl v
Statussjekk url til @Myrdrahl: Nytt felt for hvert av sublag

**Comment by bjornreppen** [comment]
Skal være på plass nå.
