### ISSUE TITLE
Sett opp CORS = * for kartlag.json

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/forvaltningsportal#216]
Det er nå ikke mulig for klienten eller andre å laste kartlag.json fra hvor som helst.  Er det lett å fikse?

**Comment by runningbones** [comment]
statiske filer som serves ut fra docker krever en -htacsess

**Comment by steinho** [comment]
From: Stein Arild Hoem <stein.hoem@artsdatabanken.no>
Sent: Sunday, June 7, 2020 19:44
To: Wouter Koch <wouter.koch@artsdatabanken.no>
Subject: SV: CORS, på ordentlig 
 
Prøv å legg in fil i katalogen for keys
.htaccess
 
Altså en fil inne i denne: http://folk.ntnu.no/wouterk/key/json/all.zip
 
Med innhold:
# to whitelist every origin, use
Header set Access-Control-Allow-Origin "*"
 
Ser ut som om apache config tillater dette on per directory basis….
Vennlig hilsen,
Stein A. Hoem
 
Stein Hoem
Seksjonsleder IT
Artsdatabanken
Postadresse: Artsdatabanken, PB1058, 7446 Trondheim
Besøksadresse: Havnegata 9, 7010 Trondheim
Tlf. 93 46 69 92

**Comment by steinho** [comment]
> Header set Access-Control-Allow-Origin "*"

Hjalp Wouter med samme problematikk litt tidligere ... fungerte for han... base httpd.conf for apache i docker imaget som brukes tillater dette...

**Comment by bjornreppen** [comment]
Takk for tips!  Fixed in https://github.com/Artsdatabanken/httpd/commit/016ec012e2c9647124409a38bde3a32e3f9d37b9
