### ISSUE TITLE
Vurder alternativt ikon på hovedkart

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/forvaltningsportal#223]
Øye-ikon er delvis missvisiende på hovedkartlag, da alle underkartlag kan være "av". I tillegg kan alle underkartlagvære "på", men vises ikke nør hovedkartlaget er "av". FKan ikon på hovedkartlag være en checkbox-aktig sak, som suppleres av et statusiokon som viser på/av og intermediate (hvis kun noen lag er "på")

**Comment by bjornreppen** [comment]
Har også tenkt på det øyeikonet som problematisk i den senere tid selv om jeg en gang argumenterte for.  Denne artikkelen argumenterer for at man bruker checkboxer for "contextual state", ting som ikke umiddelbart oppdaterer global state (f.eks. søkekriterier før man så må trykke på en søkeknapp), men toggle switcher for ting som umiddelbart oppdaterer global state som jo er tilfelle her.  https://uxmovement.com/mobile/stop-misusing-toggle-switches/

**Comment by bjornreppen** [comment]
Er denne nå løst ved at muligheten til å slå av på tjenestenivå er fjernet?
