### ISSUE TITLE
Klikk i kart - alle kartlag

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/forvaltningsportal#251]
Brukertilbakemelding: Ved kilkk i kart, alle akrtlag, gir svært mange kartlag "ingen treff". Ønsker at kartlag med "ingen treff" plasseres nederst i liste.

**Comment by bjornreppen** [comment]
Kanskje gruppere dem i ett listeelement nederst som kan klikkes på og som da erstattes med alle elementene med treff.  Eksempel:

![image](https://user-images.githubusercontent.com/281359/89014799-5c546f00-d316-11ea-8ce3-65609eedfd42.png)

![image](https://user-images.githubusercontent.com/281359/89014844-68d8c780-d316-11ea-87eb-2fed2b3a4d1d.png)
