### ISSUE TITLE
15. [Info om valgt sted] - Info fra valgte lag [10]

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/forvaltningsportal#30]
Informasjonsboks med overlappende info med valgte lag
Stort, ekspanderbart (hvis mye info) felt (infoboks) med sammenstilling av informasjon fra sted vs. valgt lag

- [x] samkjør datakilde fra alle lag (mest relevant for #33
- [x] filtrer på de markert som aktive, kjør søk på disse
- [x] presentere disse i relevant infoboks.
- [x] fremstille litt penere, og hindre for mye overlapp i boksene med #33

**Comment by helemork** [comment]
Denne har vist seg å være litt større teknisk enn tittelen indikerer, da måten dataen sendes inn og struktureres bør endres. Det som er der nå var lagt opp til en demo, og dekker derav ikke fremtidige behov. Listen nedenfor kan knyttes opp mot flere issues.

Etter rask diskusjon med @runningbones kom vi frem til følgende:

- Lokaliserer hvor lagene som sendes inn til kartet og kartlagfanene, og fjerner dem
- Legger til et lite utvalg av de kartene vi har fått klarsignal på at vi skal ha med i steden
- Sender denne inn fra en felles liste som også inneholder info som trengs for oppslag i API
- Legger ved om kartet er vist/skjult i denne lista fremfor der det var før
- På denne måten kan man lett søke i listen for å få frem kun søk i valgte lag.
- Dette vil også knyttes opp mot å legge på labels på datasettene

Fordelene med å ha et "bibliotek" som vi leverer alt fra er lettere samhandling mellom komponentene basert på hva en bruker gjør, men også at det blir lettere å legge til/fjerne lag ved fremtidig utvikling,

**Comment by runningbones** [comment]
https://github.com/Artsdatabanken/forvaltningsportal-lastejobb
og
https://github.com/Artsdatabanken/forvaltningsportal-ubehandlet

**Comment by runningbones** [comment]
Ønskeliste:
- [ ]  Avklart sted for å legge inn nye datasett
- [ ]  Standardisert oppsett for hvilke attributter/egenskaper/tags som skal registereres
- [ ]  Lastejobb som generer ny fil til bruk i portal

**Comment by runningbones** [comment]
Diksutere videre om dette bør bli en database

**Comment by helemork** [comment]
Møtereferat 30.1.2020 – Nordlys. Til stede: Ø,B,H
- hvor er datan?
. f.elks. issue nr 3
-	Forvaltningsportal lastejobb < her fikses og lastes de
-	Forvaltningsportalen metadata.json <her havner det
-	Forvaltningsportal ubehandlet < her bor de

**Comment by helemork** [comment]
Konklusjon på denne - @helemork  og @bjornreppen har nå jobbet med å :
- fjerne store mengder unødvendig kode over fra nin-kart uten at funksjon forsvinner (stor refactor)
- fjerne lastejobb, da den egentlig ikke hadde hensikt i dette prosjektet
- lage én kilde for all data (hvordan å legge til/oppdatere denne kan vi komme tilbake til senere, i første omgang var fokuset at det som er der skal funke fra en og samme plass)
- når nå alt samkjøres kan denne og den relaterte issuen #33 bli fikset. Det meste på listen på denne issuen blir nå  direkte relatert til #33, ikke denne, så det som gjenstår på denne vil ennå måtte fikses, flytter de inn i øverste kommentar så de alltid er synlige.
