### ISSUE TITLE
[Sidesøk] - Sidedekkende søk

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/forvaltningsportal#34]
UU krav. Søkebar må returnere treff i alle datasettene, inkludert sted, koordinat og annen data. Ikke kun navn på datasettene. 

# Innhold i søk
- [x] Filtrering i datasett allerede laget for kartlagfanen, beholdes inntil videre.
- [x] GEOGRAFISK SØK: Kommuner
- [x] Utrede hva som faktisk skal skje når man velger det man finner i søkeboksen.
- [x] Søk i datasett på samme måte som filtersøket, returnerer treffliste med relevante objekt med øyeknappen. Forenklet versjon av generisk_element eller nytt element med delvis samme innhold?
- #1 Ekstra søk på bnr/gnr osv, blokkerer ikke denne, kan legges til i etterkant
- #95 geografi fylker legges til fra egen issue

# Oppdatering etter diskusjon:
- [x] Ser ut som scrollbaren sluttet å virke?
- [x] 1. tittel
- [x] 2. underelemet
- [x] 3. dataeier
- [x] 4. tags
- [x] max 5 georesponser og 5 lagresponser 
- [x] Elementene i lista forenkles til å åpne et element
- [x] Å åpne element er å skjule kartlagene i kartlagfanen og dytte inn utelukkende valgt element (Bjørns forslag nr 1)
- [x] Valgt element skal ha åpnet underkategori
- [x] Valgt element skal ha pil tilbake for å ta oss ut av elementet tilbake til kartlaglisten
- [x] Søke-knapp bør denne ta deg fra dropdown til en side med søkeresultater som bruker hele kartlagfanen. X-en tar deg da tilbake til start.
- [x] Søkresultat må kunne brukes på samme måte som element i droppnedlisten, altså må noen funkjsoner flyttes ut eller opp fra søkebaren (handlegeosøk oppslag blant annet)
- [x] Søkeresultat i egen fane må presenteres mer estetisk
 
# Design av søk
- [x] Plasser over kartlagfanen på storskjerm.
- [x] Enkel tilpasning på mobil

# Relevante Spørsmål for søk
* Søk knapp utsettes til etter gnr/bnr 
* Hva skjer når man trykker på søk-knappen/enter? Velger den øverste element? Når vi får på plass bnr/gnr osv gir det jo mening at den søker med strengen direkte. men skal den i tilfeller der slikt ikke finnes gå for øvre kartlag, øvre geoplass eller returnere "ingen treff" fordi man ikke har valgt noe - med mindre strengen har en full match med noe i trefflista?

![image](https://user-images.githubusercontent.com/17450081/78035638-a7ab4080-7369-11ea-9faf-a0c7d447b93f.png)

**Comment by runningbones** [comment]
1. Fylke/kommune 
2. Stedsnavn
3. Datasett (aktive før passive?)
3a. datasettnavn før attributt?

**Comment by runningbones** [comment]
Hva skjer når du søker?
1. treffliste
2. ved valg av treff: geografi (steder og adm. geografi) pan til geografien
3: ved treff i datsett/attributt: til datasettet med mulighet for on/off

**Comment by runningbones** [comment]
Fra mandagsmøtet 20200330:

- søk via api: ssr/adresse/matrikkel + kartlag

- Søkefeltet bor over kartlagsfane på "topbar".

- Treff i kartlag gir mulighet til å  slå på/av

**Comment by runningbones** [comment]
Kan legge inn hjelp/beskrivelse i popup på søk når bruker har cursor i søkefelt, ala www.norgeskart.no.  

"Du kan søke på adresse, stedsnavn eller koordinater.
For eksempel:
Wergelandsveien1, Oslo
0301-209/416
Slottsparken
6649900,261205
For flere søkevarianter, se under tips og triks i menyen."

**Comment by helemork** [comment]
> 
> 
>     1. Fylke/kommune
> 
>     2. Stedsnavn
> 
>     3. Datasett (aktive før passive?)
>        3a. datasettnavn før attributt?

Jeg tror det er dumt å søke i aktive før passive, da man kan skru dem av og på fra denne tabben, og de da teknisk sett burde falt ut av lista, som vil bli å endre state i state, og det er ikke så bra?

**Comment by runningbones** [comment]
Svar: Enig så lenge treff kun er i kartlagets navn, men kan vel være fornuftig hvis søket går dypere?

**Comment by helemork** [comment]
@runningbones igjen, det tror jeg ikke altså. Dvs, jeg ser ikke helt fordelen med det da de som allerede er påskrudd kan vises lett med filterfunksjonene våre som skrur av andre lag, så å søke på dem blir litt som å søke på noe man allerede har funnet? Jeg vil jo tro at om man har funnet dem, trenger man ikke søke på dem. Mulig jeg tenker feil?

Kunne du og tatt en titt på de andre spørsmålene i øverste felt/hovedteksten?

**Comment by runningbones** [comment]
# Svar Relevante Spørsmål for søk
- [ ] Hva skjer når man trykker på søk-knappen/enter? Velger den øverste element? Når vi får på plass bnr/gnr osv gir det jo mening at den søker med strengen direkte. men skal den i tilfeller der slikt ikke finnes gå for øvre kartlag, øvre geoplass eller returnere "ingen treff" fordi man ikke har valgt noe - med mindre strengen har en full match med noe i trefflista?
- Tryppe på søkknaoo/enter: ingen ting skjer. Bruker må velge fra treffliste

- [ ] har nå satt max 5 georesponser og 2 lagresponser - ønsker om endring?
- max 5 i liste av hver kategori treff, men bør kunne "ekspandere" for flere treff.

- [ ] Skal vi i lagsøk etterfylle lista først fra tittel, så fra andre element (f.eks dataleverandør) og så til slutt andre tags hvis ingen element funnet ellers? Trenger en prioritering på attributtene før jeg setter opp.

- 1. tittel, 2. underelemet, 3, dataeier, 4. tags

- [ ] om man bruker knappene i droppned for et lagelement - når lukkes lista?
- når ny droppned åpnes

**Comment by bjornreppen** [comment]
Er det off-topic å spørre om Universell utforming?  Tastaturnavigering https://uu.difi.no/krav-og-regelverk/losningsforslag-web/tastaturnavigering

"I enkelte situasjoner benytter brukeren også piltastene, for eksempel for å bla seg gjennom valg i en nedtrekksliste eller hvis brukeren også har et hjelpemiddel."

![image](https://user-images.githubusercontent.com/281359/78118482-5ce00600-7407-11ea-8489-a6a99ecfa0d2.png)

**Comment by helemork** [comment]
definitivt ikke, @bjornreppen! Har følgt det vi bestemte i fjor.

Om du husker retningslinjene vi fikk i UU-gjennomgangen med han svensken (via artsobs), ble det bestemt at navigering skal skje utelukkende med TAB, da piltastene ofte brukes av f.eks nettopplesere og slikt for å navigere i interne menyer. Med andre ord vil å tillate bruk av piltastene kunne ødelegge for deres navigering, så det bør unngås. Se meget kort oppsumering her: https://github.com/Artsdatabanken/grafiskprofil/wiki/Tastaturnavigering

**Comment by bjornreppen** [comment]
Random tanker: 

- Hadde det vært realt med noen filterknapper i toppen av søkeresultatet? 
- Lage egne views for hvert kartlag som kan bruke hele kartlagvinduet, hvor man kommer tilbake til listen med en tilbake-knapp?
  - Dette vil gjøre at valg av kartlag i søkeresultat medfører at man kan "komme til elementet" etter å ha klikket på et søkeresultat.. istedet for at "ingenting" skjer.
- Jeg tror jeg ville ha droppet øye og expander i resultatlisten (Ja, det medfører 1 ekstra klikk)
  - Man unngår problematikk med at elementer "flytter seg i lista" når man slår dem av og på
- Fjernet søke-knappen, erstatte med en X for å fjerne kriterie+resultater

**Comment by helemork** [comment]
@bjornreppen, @runningbones 

> Lage egne views for hvert kartlag som kan bruke hele kartlagvinduet, hvor man kommer tilbake til listen med en tilbake-knapp? 

* Er ikke dette det vi prøvde å unngå denne gangen ved å bare ha alt i ei fin liste ? Kjenner jeg stiller meg litt skeptisk, men hva om vi legger elementet øverst i lista over en slags skillelinje når det trykkes på med en x? blir litt det samme som du foreslår, men at den ikke tar hele fanen. Som i at elementene i droppned har en pil på seg, trykker på elementene, lukker meny og legger elementet øverst i kartlag (kanskje til og med over teksten kartlag) i en dedikert boks med x i hjørnet som heter søkeresultat eller valgt lag eller et eller anna? kan tegne et utkast om dere ikke forstår meg. 

> Jeg tror jeg ville ha droppet øye og expander i resultatlisten (Ja, det medfører 1 ekstra klikk) 

* Absolutt enig hvis man har en måte å "komme seg til elementene", hvis ikke vet jeg ikke helt hva vi skal gjøre med dem ved klikk. Rett og slett for at droppneden skal oppføre seg nettopp som en droppned, og det går under "elementer skal kodes som det de er"-retningslinjene til difi.

> Fjerne søke-knappen, erstatte med en X som dukker opp når man er på en underside. 

* Vi har vel bytet den ut med en x i søkefeltet nå, men den bør kanskje skjules når teksen ikke er der. Hvis vi går for søkeside som du sier gir det mening. Hvis ikke blir denne løsningen litt off. Tenke på det når vi har bestemt flowen på det ovenfor!

> Hvis man skal ha en søke-knapp bør denne ta deg fra den enkle dropdown til en side med søkeresultater som bruker hele kartlagfanen. X-en tar deg da tilbake til start. 

* Helt enig. Denne gir mening. Vi kan vurdere noe sånt når vi får lagt til bnr/gnr osv, da vil det nok bli nødvendig.

--- og til slutt, en liten brukertest kan jo hjelpe oss litt her. Jeg bor med 3 stykk som er veldig gode til å trykke på knapper og fortelle hva de vil skal skje. Det er ofte ikke det jeg tror :D

**Comment by runningbones** [comment]
@bjornreppen sin liste:
1. spenende forslag, som også kan løse en del utfordrnger vi vil få npr noen kartlag er tjenestebasert, mens andre forvaltes  lokal db - dette vil gi ulik grad av funksjonalitet, og èn uniform liste vil være vanskelig å oppnå.
2. Kan vi komme oss rett til riktig element, er jeg enig
3. Får vi egen søkeside, en topp forslag
4. Egen søkeside/resultatside med filter høres bra ut!
