### ISSUE TITLE
[Faktaark og produktark] 

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/forvaltningsportal#36]
Tilgjengelige faktaark for hvert datasett
Ikon for faktaark som kan ekspanderes
Visning av faktaarket. Enten i samme fane, eller i fjernbar ekstrafane på venstresiden

- [x] Ferdigstilt i #86 
- [x] Legg til produktark

**Comment by runningbones** [comment]
Gjerne også embed/iframe-aktig sak.

**Comment by helemork** [comment]
- legg til databasefelt
Ø legger inn dbfeltene
