### ISSUE TITLE
Pakken node-gyp bruker python2. Kunne du oppdatert det, da python2 er død?

### ISSUE THREAD

**Issue by bjornreppen** [Artsdatabanken/forvaltningsportal#43]
Ser ut som det er bare *node-sass* som er avhengig av *node-gyp*, og *node-sass* vil ha en gammel versjon av *node-gyp* som avhenger av *python2*.  

Vente, eller la være å bruke *node-sass*?

https://github.com/sass/node-sass/issues/2716

```
$ npm ls
├─┬ node-sass@4.13.0
│ ├─┬ node-gyp@3.8.0
│ │ ├─┬ fstream@1.0.12
 
```

**Comment by helemork** [comment]
Aner ikke hva vi har bruk for, så opp til deg. 😊 u fix?
