### ISSUE TITLE
Data 3. Errorbeskjed/Feilmeldinger/Loadingikon

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/forvaltningsportal#53]
Finn ut om vi trenger eller hva som skjer med errorbeskjed / loadingikon etter sammenslåing, når alt kommer via en resultatliste som byttes ut ved nytt klikk fremfor å ligge der og vente på deg fra forrige klikk

**Comment by bjornreppen** [comment]
Finner ut at koden er utkommentert:

```
    /* Tror muligens ikke disse trigges/er i bruk nå, usikker. @bjørn? 
    :+1
    if (resultat.error)
      return <ErrorItem title={primary_text} message={resultat.error}></ErrorItem>;
    if (resultat.loading) return <LoadingItem title={primary_text} />;*/
```

**Comment by helemork** [comment]
@bjornreppen , den ble kommentert ut fordi den IKKE virket :D 
Poenget med denne issuen var å få den til å eventuelt virke igjen. 
Loadingikon antar jeg bør rotere så lenge en av queriene ikke har returnert nederst under listen? Altså fra søk start til søk slutt? Siden vi ikke har listen før den returnerer. 

Errorbeskjeden bør vel returneres i punktene som ikke har respons?
