### ISSUE TITLE
Data 1. Nytt API NiN-data

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/forvaltningsportal#55]
Generer nytt api for arb lag så de kan søkes opp enkeltvis uten å få med alt av nin-data.

**Comment by bjornreppen** [comment]
nytt API: https://github.com/Artsdatabanken/punkt-oppslag-api/commit/27f7b46bf8695fc52369cafcc85ee1079a661522

**Comment by bjornreppen** [comment]
Oppgradering av avhengigheter: https://github.com/Artsdatabanken/nin-kart/commit/1930774e339dc28e9253769ddf6664f8552be682
