### ISSUE TITLE
Data 5. Bakgrunnskart Geonorge

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/forvaltningsportal#56]
https://kartkatalog.geonorge.no/?type=service&type=servicelayer&organization=Kartverket&DistributionProtocols=WMTS-tjeneste&dataaccess=Norge%20digitalt-begrenset&dataaccess=%C3%85pne%20data

De fleste aktuelle har følgende adresse: https://opencache.statkart.no/gatekeeper/gk/gk.open_wmts?request=GetCapabilities&service=wmts

Begynn med: 

- [x] GEBCO
- [x] TOPO 4 
- [x] TOPO 4 Graatone
- [x] Fjellskygge

Norgeibilder trenger tilsynelatende token.

**Comment by bjornreppen** [comment]
Status:
- 3 Kartlag synlige
- Gebco fikk jeg ikke til å virke, la inn havbunn_grunnkart, denne inneholder kanskje gebco + mer?
- Fjellskygge fikk jeg heller ikke til å virke (i QGIS eller kode)
- Norge i bilder har jeg ikke klart å finne i EPSG:3857, eventuelt vurdere å bytte projeksjon på hele løsningen?  Leaflet -> OpenLayers f.eks
- Avklar: Hvilket token skal brukes?

**Comment by runningbones** [comment]
@steinho kan kanskje bistå med token-løsning?

**Comment by bjornreppen** [comment]
Greit å være klar over at akkurat disse kartene ikke vil fungere for brukere med verktøy som f.eks. EFF PrivacyBadger installert. Jeg har ikke undersøkt hvorfor de handler på svartelista.  Så og si alt av andre websider fungerer.  https://github.com/kartverket/norgeskart.no/issues/20
