### ISSUE TITLE
Finne ut hva som faktisk skal gjøres og hva vi starter med

### ISSUE THREAD

**Issue by helemork** [Artsdatabanken/forvaltningsportal#7]
- [x] Finne noen tasks å starte med
- [x] Finne ut hvilken flyt vi ønsker på portalen
- [x] Finne ut hva vi faktisk skal fremstille

**Comment by runningbones** [comment]
Litt mer tungvindt å flytte issues enn forutsatt. Ser ut til at de må taes en for wen, og mister labels i overføringa (er vel eg. oppretting av nye issues som skjer). Jobbert med saken

**Comment by helemork** [comment]
Helene har nå laget et dokument.
Foreslår å fjerne ALLE gamle issues og legge inn fra dette i steden da det er mer hensiktsmessig.
