### ISSUE TITLE
Django - Oppdater databasefelt

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/forvaltningsportal#91]
Oppdatere databasemodellene:
- [x] Legg til felt for lenke for geonorge-url
- Faktaark er tilstrekkelig, men her trengs en sikring for faktaark url'er som har xml - se #36
- [x] Legg til felt for lenke til legende (tegnforklaring på norsk?)
- [x] Legg til felt med checkbox for test/prod?
- I tilfeller hvor vi hoster data selv, bruk på samme måte som ellers men lenke til den. Trenger ikke markeres.

**Comment by helemork** [comment]
- forklaring på karttjenester må vi legge til

**Comment by runningbones** [comment]
Skal lenke til Geonorge ligge her? : ja

 Er feltene for lenke til karttjenester tilstrekkelig? legg inn forklaring

 Er felt for faktaark tilstrekkelig? bedre forklaring

 Lenke til legend? ja

 Checkbox for test/prod? ja

 Skal egenskaoer/tags for kartlag som ligger i egen DBcache forvaltes her? behov for checkbox? Lenker til egne api!

**Comment by helemork** [comment]
Jeg legger inn svarene i første beskjed som todo, så det kommer opp i projectboardene
