### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/forvaltningsportal#92]
Hva skal deployes, jf. trøbbel med django i docker?
Hvor ofte skal vi deploye til test?
Hvordan unngå at vi deployer en annen applikasjon?

**Comment by bjornreppen** [comment]
Er vi fornøyd med denne nå, eller har vi fortsatt utfordringer?

**Comment by helemork** [comment]
Hvor går jeg for å teste? Hva er url for forv.port og forv.port test?

**Comment by bjornreppen** [comment]
https://github.com/Artsdatabanken/forvaltningsportal/pull/101
