### ISSUE TITLE
Brukertesting/brukertilbakemelding via webskjema

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/forvaltningsportal#93]
I tida som kommer vil vi ha behov for brukertilbakemeldinger. Har fått tilbakemelding fra Mdir om at brukerterskel for innlegging av issues via github er krevende. Kan vi tilrettelegge et webskjema el.l. som   poster nye issues på vårt repo ala https://gist.github.com/bmcbride/62600e48274961819084

Kan ved en slik funksjon "skreddersy" hva vi ønsker tilbakemelding på , og har tro på at dette er noe  som kan gjenbrukes på alle våre applikasjoner med github repo.

**Comment by helemork** [comment]
Jeg vil si det er flere faser i dette:
1. Ordentlig brukertest
Jeg foreslår at vi lager et enkelt spørreskjema via google docs eller noe uten noen form for innlogging. 
Lager testscenario, ber dem prøve dem, og lager ting de kan fylle ut. Meget god erfaring med det fra tidligere.

2. Når siden er litt mer ferdig: vurdere slikt som ovenfor med direkte issues. Men til å begynne med er det bedre at vi ser over hva de mener som gruppe enn at de selv setter opp issues. Når ting er litt mer ferdig, derimot, er det fint om de kan legge dem inn selv. Men ofte kan ting de ha problem med være i backloggen fra før osv, da vil ekstra issues bli litt tungvindt

**Comment by helemork** [comment]
# Oppsumerte resultater fra brukertesting av søkefunksjonen (utelukkende):

Kjørte test på 3 individ, alle direkte tilgjengelige i min umiddelbare nærhet.

## Test nummer 1:
- Kvinne, 67, meget glad i kart og bruker av NGUs tjenester, men ikke så vant med nye nettløsninger. Anser seg selv som imålgruppen for applikasjonen

1. Slet med å forstå terminologien, spesielt hva en søkebar er, og dermed med å finne den.
2. Mente søkebaren var litt for godt gjemt øverst i hjørnet, og hadde sett at den ble tydeliggjort litt mer med enten litt tydeligere omriss eller større fontstørrelse på teksten.
3. Ved bruk av søk, forventet hun at sitt fylke skulle være tilgjengelig allerede på første bokstav. Mente vi må tydeliggjøre at ikke alle alternativ vises til enhver tid.
4. Foretrakk å prøve å finne ting i listene fremfor søkebaren hvis mulig, og forsøkte heller å filtrere/søke på der overskriftene er. Når kartlaglisten er usortert er det forøvrig ikke nødvendig med overskriften da den heller ble ansett som forvirrende. Overskriftene gir kun mening når det er valgt en sortering.
5. Slet veldig med å finne av/på knappen til kartlagene, da hun ikke gjenkjente øye-ikonet, og ikke forstod det var en knapp. Hun mente forøvrig at det burde være nok å nevne det i en brukerforklaring, for så fort det ble forklart syntes hun det ga mening.
6. Synes tilbakeknappene fungerte fint.
7. Ønsket utelukkende å tømme søkebaren via backspace, og velge element via droppned. Ignorerte de to knappene, men fikk til å bruke dem på direkte oppfordring. 
8. Mente ting hadde potensiale, menble litt skuffet over å ikke kunne søke på f.eks stedsnavn, som forøvrig ligger i vår todo-liste. 
9. Likte ikke at stedsnavn og kartlag ble blandet i søkebaren, mente man enten 
  - burde ha tydelig underoverskrifter mellom kategoritypene
  - burde velge på forhånd hva man søkte i (checkboxer eller noe filter for geo/lag) osv
  - hadde lyst å søke på f.eks "bare geologi" (altså kun tema/tags)

**Comment by helemork** [comment]
Lukker denne for nå. Vi må naturlig nok ha mer brukertesting senere, men da kan vi sette opp ny issue når den tid kommer :)
