### ISSUE TITLE
OmrådeAPI med fylker

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/forvaltningsportal#95]
Søk på fylker bør gi mulighet for zoom til/pan. Kan kajnskje løses ved at OmrådeAPI inneholder flylker med geometri. BBox, vektet senterpunkt og/eller hele objektet.

**Comment by helemork** [comment]
Denne er et underpunkt på #34

**Comment by bjornreppen** [comment]
For eksempel kan vi gjøre noe sånt: https://forvaltningsportalapi.test.artsdatabanken.no/rpc/oppslag?q=%ron%

**Comment by helemork** [comment]
@bjornreppen 
Det apiet du har satt  opp der: 
- inneholder ikke alle fylkene
- mangler fylkeskodene

Topp at polygonene er med, slipper doble oppslag som på kommuner, men er det kanskje er hensiktsmessig å ha med fylkeskoder?

Og kan vi legge til alle? Eller blir datasettet litt stort? 
På kommune gfår vi bare navn + kode, og så gjør vi oppslag på kommunenr som gir oss koordinatene. Mulig det er hensiktsmessig?

**Comment by bjornreppen** [comment]
Sjekker
